apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistentvolume-wordpress
  namespace: wordpress-namespace
spec:
  storageClassName: manual
  capacity:
     storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: '/data-wordpress'
