apiVersion: v1
kind: Pod
metadata:
   name: mysql-pv
spec:
  containers:
    - image: mysql
      name: mysql
      volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-data
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: rokhaya
        - name: MYSQL_DATABASE
          value: eazytraining
        - name: MYSQL_USER
          value: rayatou
        - name: MYSQL_PASSWORD
          value: rokhaya
  volumes:
    - name: mysql-data
      persistentVolumeClaim:
        claimName: pvc
         
